AWSTemplateFormatVersion: 2010-09-09

Description: CiCd Pipeline for ECR/ECS

Resources:

  #
  # S3
  # 
  EcrDemoCodePipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: ecs-demo-codepipeline-artifact-bucket-gk-deckers  

  #
  # ECR
  #

  EcrDemoRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ecs-demo-repo

  #
  # Code Build
  #

  EcrDemoCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-demo-codebuild-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      Path: /  
      
  EcrDemoCodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ecs-demo-codebuild-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: !Sub arn:aws:logs:*:${AWS::AccountId}:*
          - Action: 
              - s3:*
            Effect: Allow
            Resource:
              - !GetAtt EcrDemoCodePipelineArtifactStore.Arn
              - !Join [ '', [ !GetAtt EcrDemoCodePipelineArtifactStore.Arn, '/*' ] ]
          - Action:
              - ecr:*
            Effect: Allow
            Resource: '*'
              #- !GetAtt EcrDemoRepository.Arn
      Roles:
        - !Ref EcrDemoCodeBuildRole         

  EcrDemoCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        ArtifactIdentifier: docker-build
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
          - Name: AWS_DEFAULT_REGION
            Value: !Ref 'AWS::Region'
          - Name: IMAGE_REPO_NAME
            Value: !Ref EcrDemoRepository
          - Name: IMAGE_TAG
            Value: latest
      Name: ecs-demo-codebuild-project
      ServiceRole: !Ref EcrDemoCodeBuildRole
      Source:
        BuildSpec: buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  #
  # CodePipeline
  # 

  EcrDemoCodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: ecr-demo-flagscript-github
      ProviderType: GitHub

  EcrDemoCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-demo-codepipeline-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Path: /  

  EcrDemoCodePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ecs-demo-codepipeline-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codestar-connections:UseConnection
            Effect: Allow
            Resource: 
              - !GetAtt EcrDemoCodeStarConnection.ConnectionArn
          - Action:
              - codebuild:*
            Effect: Allow
            Resource: !GetAtt EcrDemoCodeBuildProject.Arn
          - Action:
              - cloudformation:*
              - iam:ListRoles
            Effect: Allow
            Resource: '*'
          - Action:
              - ecr:*
            Effect: Allow
            Resource:
              - !GetAtt EcrDemoRepository.Arn            
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !GetAtt EcrDemoCodePipelineArtifactStore.Arn
              - !Join [ '', [ !GetAtt EcrDemoCodePipelineArtifactStore.Arn, '/*' ] ]
      Roles:
        - !Ref EcrDemoCodePipelineRole

  EcrDemoCodePipeline:
    Type: AWS::CodePipeline::Pipeline 
    Properties:
      ArtifactStore: 
        Location: !Ref EcrDemoCodePipelineArtifactStore
        Type: S3
      Name: ecr-demo-codepipeline
      RoleArn: !GetAtt EcrDemoCodePipelineRole.Arn
      Stages: 

        - Name: Source
          Actions:
            - ActionTypeId:
                Version: '1'
                Owner: AWS
                Category: Source
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !GetAtt EcrDemoCodeStarConnection.ConnectionArn
                FullRepositoryId: flagscript/ecs-cics-demo
                BranchName: master
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
              Name: GitHubSourceCode

        - Name: Build
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration: 
                ProjectName: !Ref EcrDemoCodeBuildProject
                PrimarySource: SourceArtifact
              InputArtifacts: 
                - Name: SourceArtifact
              Name: BuildDockerPublishEcr
              OutputArtifacts: 
                - Name: BuildArtifact
              RunOrder: 1

        - Name: Deploy
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                StackName: ecs-cicd-demo-cluster
                TemplatePath: DeploymentArtifacts::cloudformation/setup-fargate.yml                
              InputArtifacts: 
                - Name: SourceArtifact
              Name: CreateFargate
              RunOrder: 1        
